<Project>
  <ItemGroup>
    <PackageReference Update="Autofac" Version="4.9.4" />
    <PackageReference Update="Autofac.Extras.Moq" Version="4.3.0" />
    <PackageReference Update="coverlet.collector" Version="8.0.1" />
    <PackageReference Update="FluentAssertions" Version="5.10.0" />
    <PackageReference Update="Microsoft.ApplicationInsights.AspNetCore" Version="2.23.0" />
    <PackageReference Update="Microsoft.AspNetCore.Mvc.Versioning" Version="5.0.0" />
    <PackageReference Update="Microsoft.ApplicationInsights" Version="2.23.0" />
    <PackageReference Update="Microsoft.Extensions.Logging.Abstractions" Version="10.0.5" />
    <PackageReference Update="Microsoft.Build.Utilities.Core" Version="18.4.0" />
    <PackageReference Update="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
    <PackageReference Update="Microsoft.Extensions.Hosting" Version="10.0.5" />
    <PackageReference Update="Microsoft.Extensions.Logging" Version="10.0.5" />
    <PackageReference Update="Microsoft.Extensions.Logging.AzureAppServices" Version="10.0.5" />
    <PackageReference Update="Microsoft.Extensions.Logging.EventLog" Version="10.0.5" />
    <PackageReference Update="Microsoft.Win32" Version="2.0.1" />
    <PackageReference Update="Microsoft.Win32.Registry" Version="5.0.0" />
    <PackageReference Update="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageReference Update="Microsoft.ServiceFabric" Version="11.0.2707" />
    <PackageReference Update="Microsoft.ServiceFabric.AspNetCore.Kestrel" Version="8.0.2707" />
    <PackageReference Update="Microsoft.ServiceFabric.Services" Version="8.0.2707" />
    <PackageReference Update="Microsoft.VisualStudio.Azure.Fabric.MSBuild" Version="1.7.9" />
    <PackageReference Update="Moq" Version="4.20.72" />
    <PackageReference Update="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Update="StyleCop.Analyzers" Version="1.2.0-beta.556" />
    <PackageReference Update="System.Fabric" Version="5.0.1-preview-01" />
    <PackageReference Update="System.Text.Encodings.Web" Version="10.0.5" />
    <PackageReference Update="xunit" Version="2.9.3" />
    <PackageReference Update="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageReference Update="Yarp.ReverseProxy" Version="2.3.0" />
  </ItemGroup>
</Project>