<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>SFYarp.FabricDiscovery</RootNamespace>
    <Platform Condition=" '$(Platform)' == '' ">x64</Platform>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="System.Linq.Async" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FabricDiscovery.Service\FabricDiscovery.Service.csproj" />
    <ProjectReference Include="..\Tests.Common\Tests.Common.csproj" />
  </ItemGroup>

</Project>
